[package]
name = "voltguard-core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
voltguard-api = { path = "../voltguard-api" }
voltguard-hal = { path = "../voltguard-hal" }
